modified:   four.c
	Make checkpatch happy, so that we can get this module upstream (hahaha!)

	$ checkpatch.pl --no-tree -f four.c

	ERROR: trailing whitespace
	 13: FILE: four.c.orig:13:
	+    $

	ERROR: trailing whitespace
	 14: FILE: four.c.orig:14:
	+    $

	ERROR: trailing whitespace
	 20: FILE: four.c.orig:20:
	+    $

	ERROR: trailing whitespace
	 24: FILE: four.c.orig:24:
	+    $

	ERROR: trailing whitespace
	 35: FILE: four.c.orig:35:
	+    $

	ERROR: trailing whitespace
	 38: FILE: four.c.orig:38:
	+    $

	ERROR: trailing whitespace
	 65: FILE: four.c.orig:65:
	+          $

	ERROR: trailing whitespace
	 69: FILE: four.c.orig:69:
	+      $

	ERROR: trailing whitespace
	 81: FILE: four.c.orig:81:
	+          $

	ERROR: trailing whitespace
	 110: FILE: four.c.orig:110:
	+          $

	ERROR: trailing whitespace
	 124: FILE: four.c.orig:124:
	+  $

	ERROR: trailing whitespace
	 174: FILE: four.c.orig:174:
	+    $

	ERROR: trailing whitespace
	 220: FILE: four.c.orig:220:
	+    $

	ERROR: trailing whitespace
	 228: FILE: four.c.orig:228:
	+  $

	ERROR: trailing whitespace
	 229: FILE: four.c.orig:229:
	+  $

	ERROR: trailing whitespace
	 230: FILE: four.c.orig:230:
	+  $

	ERROR: trailing whitespace
	 233: FILE: four.c.orig:233:
	+          $

	ERROR: trailing whitespace
	 237: FILE: four.c.orig:237:
	+        $

	ERROR: trailing whitespace
	 242: FILE: four.c.orig:242:
	+  $

	ERROR: trailing whitespace
	 248: FILE: four.c.orig:248:
	+      $

	ERROR: trailing whitespace
	 268: FILE: four.c.orig:268:
	+      $

	ERROR: trailing whitespace
	 294: FILE: four.c.orig:294:
	+      $

	ERROR: trailing whitespace
	 443: FILE: four.c.orig:443:
	+      $

	ERROR: trailing whitespace
	 514: FILE: four.c.orig:514:
	+    $

	ERROR: trailing whitespace
	 833: FILE: four.c.orig:833:
	+    $

	ERROR: trailing whitespace
	 834: FILE: four.c.orig:834:
	+    $

	ERROR: trailing whitespace
	 835: FILE: four.c.orig:835:
	+    $

	total: 27 errors, 0 warnings, 838 lines checked

	NOTE: whitespace errors detected, you may wish to use scripts/cleanpatch or
	      scripts/cleanfile

	four.c.orig has style problems, please review.

	If any of these errors are false positives, please report
	them to the maintainer, see CHECKPATCH in MAINTAINERS.

	Signed-off-by: Christian Kujau <lists@nerdbynature.de>